# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources/ui/activation_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(671, 315)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main/license.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("QDateEdit {\n"
"    border: 1px solid #7cd0ef;\n"
"    border-radius: 5px;\n"
"}\n"
"QDateEdit:hover{\n"
"border-color: #5487ee;\n"
"}\n"
"\n"
"\n"
"QDateEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
" \n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"\n"
"\n"
"QDateEdit::down-arrow {\n"
"  image: url(:/main/drop_down.png);\n"
"height: 18px;\n"
"width: 18px;\n"
"}\n"
"QDateEdit::drop-down:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d8d7d7, stop: 1 #e9e9e9);\n"
"}\n"
"\n"
"QDateEdit::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.horizontalLayout_2.addWidget(self.title)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.start_date = QtWidgets.QDateEdit(Dialog)
        self.start_date.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.start_date.setFont(font)
        self.start_date.setCalendarPopup(True)
        self.start_date.setObjectName("start_date")
        self.horizontalLayout_29.addWidget(self.start_date)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem2)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_29.addWidget(self.label_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem3)
        self.end_date = QtWidgets.QDateEdit(Dialog)
        self.end_date.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.end_date.setFont(font)
        self.end_date.setCalendarPopup(True)
        self.end_date.setObjectName("end_date")
        self.horizontalLayout_29.addWidget(self.end_date)
        self.horizontalLayout.addLayout(self.horizontalLayout_29)
        self.ok_button = QtWidgets.QPushButton(Dialog)
        self.ok_button.setMinimumSize(QtCore.QSize(40, 40))
        self.ok_button.setMaximumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ok_button.setFont(font)
        self.ok_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("border: 1px solid rgb(218, 218, 218);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout.setHorizontalSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.given_text = QtWidgets.QLineEdit(self.frame)
        self.given_text.setMinimumSize(QtCore.QSize(0, 40))
        self.given_text.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        self.given_text.setFont(font)
        self.given_text.setStyleSheet("\n"
"QLineEdit{\n"
"background-color: white;\n"
"border: 1px solid #59CDF2;\n"
"\n"
"border-bottom-left-radius:5px;\n"
"border-top-left-radius:5px;\n"
"border-right: None;\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border: 1px solid #29e1ff;\n"
"border-right: None;\n"
"}")
        self.given_text.setPlaceholderText("")
        self.given_text.setClearButtonEnabled(False)
        self.given_text.setObjectName("given_text")
        self.horizontalLayout_4.addWidget(self.given_text)
        self.copy_button = QtWidgets.QPushButton(self.frame)
        self.copy_button.setMinimumSize(QtCore.QSize(35, 40))
        self.copy_button.setMaximumSize(QtCore.QSize(35, 16777215))
        self.copy_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.copy_button.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border: 1px solid #59CDF2;\n"
"border-left:None;\n"
"border-bottom-right-radius:5px;\n"
"border-top-right-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(234, 234, 234);\n"
"border: 1px solid #59CDF2;\n"
"border-left:None;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(225, 225, 225);\n"
"border: 1px solid #59CDF2;\n"
"border-left:None;\n"
"}")
        self.copy_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/main/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.copy_button.setIcon(icon1)
        self.copy_button.setIconSize(QtCore.QSize(28, 28))
        self.copy_button.setObjectName("copy_button")
        self.horizontalLayout_4.addWidget(self.copy_button)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.encoded_text = QtWidgets.QLineEdit(self.frame)
        self.encoded_text.setMinimumSize(QtCore.QSize(0, 40))
        self.encoded_text.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        self.encoded_text.setFont(font)
        self.encoded_text.setStyleSheet("\n"
"QLineEdit{\n"
"background-color: white;\n"
"border: 1px solid #59CDF2;\n"
"\n"
"border-bottom-left-radius:5px;\n"
"border-top-left-radius:5px;\n"
"border-right: None;\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border: 1px solid #29e1ff;\n"
"border-right: None;\n"
"}")
        self.encoded_text.setPlaceholderText("")
        self.encoded_text.setClearButtonEnabled(False)
        self.encoded_text.setObjectName("encoded_text")
        self.horizontalLayout_5.addWidget(self.encoded_text)
        self.paste_button = QtWidgets.QPushButton(self.frame)
        self.paste_button.setMinimumSize(QtCore.QSize(35, 40))
        self.paste_button.setMaximumSize(QtCore.QSize(35, 16777215))
        self.paste_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.paste_button.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border: 1px solid #59CDF2;\n"
"border-left:None;\n"
"border-bottom-right-radius:5px;\n"
"border-top-right-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(234, 234, 234);\n"
"border: 1px solid #59CDF2;\n"
"border-left:None;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(225, 225, 225);\n"
"border: 1px solid #59CDF2;\n"
"border-left:None;\n"
"}")
        self.paste_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/main/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.paste_button.setIcon(icon2)
        self.paste_button.setIconSize(QtCore.QSize(28, 28))
        self.paste_button.setObjectName("paste_button")
        self.horizontalLayout_5.addWidget(self.paste_button)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        self.activate_button = QtWidgets.QPushButton(self.frame)
        self.activate_button.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.activate_button.setFont(font)
        self.activate_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.activate_button.setStyleSheet("QPushButton {\n"
"background-color: white;\n"
"border-radius: 5px;\n"
"border: 2px solid #6AF2F0;\n"
"}\n"
"QPushButton:hover {\n"
"color: white;\n"
"background-color: #6AF2F0;\n"
"}\n"
"QPushButton:pressed {\n"
"color: white;\n"
"background-color: rgb(47, 231, 247);\n"
"border: 2px solid rgb(47, 231, 247);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/main/key.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.activate_button.setIcon(icon3)
        self.activate_button.setIconSize(QtCore.QSize(30, 30))
        self.activate_button.setObjectName("activate_button")
        self.gridLayout.addWidget(self.activate_button, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Aktivlashtirish"))
        self.title.setText(_translate("Dialog", "Litsenziya qo\'shish"))
        self.start_date.setDisplayFormat(_translate("Dialog", "dd/MM/yyyy"))
        self.label_5.setText(_translate("Dialog", "-"))
        self.end_date.setDisplayFormat(_translate("Dialog", "dd/MM/yyyy"))
        self.ok_button.setText(_translate("Dialog", "OK"))
        self.activate_button.setText(_translate("Dialog", "Aktivlashtirish"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
