# Generated by Django 3.2.13 on 2022-05-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nomi')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('quantity', models.FloatField(default=0, verbose_name='Qolgan soni')),
                ('last_added_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
