# Generated by Django 3.2.13 on 2022-05-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='order',
            name='cash_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='credit_card',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='debt_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='printer',
            field=models.CharField(blank=True, default='XP-80', max_length=250, null=True, verbose_name='Printer'),
        ),
    ]
