# Generated by Django 3.2.13 on 2022-05-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='printer',
            field=models.CharField(blank=True, default='XP-80', max_length=250, null=True, verbose_name='Printer'),
        ),
    ]
