# Generated by Django 3.2.12 on 2022-05-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_added_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
