# Generated by Django 3.2.13 on 2022-05-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20220511_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cash_money',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='credit_card',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='debt_money',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
