# Generated by Django 3.2.13 on 2022-05-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_category_printer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='order',
            name='cash_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='credit_card',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='debt_money',
            field=models.IntegerField(default=0),
        ),
    ]
