# Generated by Django 3.2.12 on 2022-05-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220510_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='printer',
            field=models.CharField(blank=True, default='Canon LBP6030/6040/6018L', max_length=250, null=True, verbose_name='Printer'),
        ),
    ]
