# Generated by Django 3.2.13 on 2022-04-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_category_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='printing_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='printer',
            field=models.CharField(blank=True, default='EPSON L805 Series', max_length=250, null=True, verbose_name='Printer'),
        ),
    ]
