# Generated by Django 3.2.13 on 2022-05-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220511_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cash_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='credit_card',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='debt_money',
            field=models.IntegerField(default=0),
        ),
    ]
