# Generated by Django 3.2.12 on 2022-04-16 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0003_auto_20220416_1012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Worker',
        ),
        migrations.AlterField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Offitsant'),
        ),
    ]
