# Generated by Django 3.2.12 on 2022-04-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_category_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='printing_required',
            field=models.BooleanField(default=False),
        ),
    ]
