# Generated by Django 3.2.12 on 2022-05-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_category_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='service_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='tax_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='printer',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Printer'),
        ),
    ]
