# Generated by Django 3.2.13 on 2022-05-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20220511_1658'),
        ('web', '0004_auto_20220511_2126'),
    ]

    operations = [
    ]
