# Generated by Django 3.2.12 on 2022-04-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20220424_1209'),
        ('web', '0004_category_printing_required'),
    ]

    operations = [
    ]
