# Generated by Django 3.2.13 on 2022-05-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_merge_0004_auto_20220511_1658_0004_auto_20220511_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='initial_payment',
            field=models.IntegerField(default=0),
        ),
    ]
