# Generated by Django 3.2.12 on 2022-05-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_table_initial_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='spent_time',
            field=models.IntegerField(default=0),
        ),
    ]
