# Generated by Django 3.2.12 on 2022-05-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_order_spent_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waiter_fee',
            field=models.IntegerField(default=0),
        ),
    ]
