# Generated by Django 3.2.13 on 2022-04-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_category_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Naqd'), ('credit_card', 'Kartadan')], default='cash', max_length=25, verbose_name="To'lov turi"),
        ),
        migrations.AlterField(
            model_name='category',
            name='printer',
            field=models.CharField(blank=True, default='EPSON L805 Series', max_length=250, null=True, verbose_name='Printer'),
        ),
    ]
