# Generated by Django 3.2.12 on 2022-04-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='printer',
            field=models.CharField(blank=True, default='Canon LBP6030/6040/6018L (Copy 2)', max_length=250, null=True, verbose_name='Printer'),
        ),
    ]
