# Generated by Django 3.2.13 on 2022-05-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_category_printer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='expensereason',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['title'], 'verbose_name': 'Taom', 'verbose_name_plural': 'Taomlar'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id'], 'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['title'], 'verbose_name': 'Xona', 'verbose_name_plural': 'Xonalar'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['-number'], 'verbose_name': 'Stol', 'verbose_name_plural': 'Stollar'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['position'], 'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.AlterField(
            model_name='category',
            name='printer',
            field=models.CharField(blank=True, default='EPSON L805 Series', max_length=250, null=True, verbose_name='Printer'),
        ),
    ]
