# Generated by Django 3.2.13 on 2022-05-02 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20220502_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['number'], 'verbose_name': 'Stol', 'verbose_name_plural': 'Stollar'},
        ),
    ]
