# Generated by Django 3.2.13 on 2022-05-09 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_table_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('table', 'Stol'), ('pickup', 'Olib ketish')], default='table', max_length=25),
        ),
        migrations.AlterField(
            model_name='category',
            name='printer',
            field=models.CharField(blank=True, default='XP-80', max_length=250, null=True, verbose_name='Printer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='web.table', verbose_name='Stol'),
        ),
    ]
