# Generated by Django 3.2.13 on 2022-05-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20220509_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='abstract_amount',
            field=models.IntegerField(null=True),
        ),
    ]
