from web import views
from django.urls import path, re_path

urlpatterns = [
    path('', views.signin, name='signin'),
    path('logout', views.logoutUser, name='logout'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('orders', views.orders, name='orders'),
    path('rooms', views.rooms, name='rooms'),
    path('room', views.room, name='room'),
    path('income', views.income, name='income'),
    path('worker', views.worker, name='worker'),
    path('expenses/', views.expenses, name='expenses'),
    path('document', views.document, name='document'),
    path('product/', views.product, name='product'),
    path('worker/add', views.user_new, name='user_new'),
    path('worker/<int:pk>/', views.user_edit, name='user_edit'),
    path('worker/<int:pk>/delete', views.user_delete, name='user_delete'),
    path('category/<int:pk>/', views.category_edit, name='category'),
    path('category/new/', views.category_new, name="category_new"),
    path('category/<int:pk>/delete', views.category_delete, name="category_delete"),
    path('product/food/<int:pk>/', views.food_edit, name='food_edit'),
    path('product/food/new/', views.food_new, name="food_new"),
    path('product/<int:pk>/delete', views.food_delete, name="food_delete"),
    path('rooms/new', views.room_new, name='room_new'),
    path('rooms/<int:pk>/tables', views.room_tables, name='room_tables'),
    path('rooms/<int:pk>/', views.room_edit, name='room_edit'),
    path('rooms/<int:pk>/delete', views.room_delete, name='room_delete'),
    path('rooms/<int:pk>/table_new', views.table_new, name='table_add'),
    path('rooms/<int:pk_room>/tables/<int:pk_table>/delete', views.table_delete, name='table_delete'),
    path('orders/<int:pk>/view', views.order_view, name='order_view'),
    path('orders/<int:pk>/complete', views.complete_order, name='order_complete'),
    path('printing/<int:order_id>/order', views.print_order, name='print_order'),
    path('expenses/new_expense_reason/', views.expense_reason_new, name='expense_reason_new'),
    path('expenses/reasons/<int:pk>/', views.expense_reason_edit, name='expense_reason_edit'),
    path('expenses/new_expense/', views.expense_new, name='expense_new'),
    path('expenses/<int:pk>/delete', views.expense_delete, name='expense_delete'),
    path('expenses/reason/<int:pk>/delete', views.expense_reason_delete
         , name='expense_reason_delete'),

]
